SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6464E08C81655433}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6518F7526EC41AB1}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6518F7526EC41A1B}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{652D313D50DF3A56}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{698AB1CE3D6969EB}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{698AB1CE3D69685E}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6206E29D69ACFBB7}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6586CAD158BD4383}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6586CAD158BD433A}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6507243BDAE1A320}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6518F7526F04D9FC}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6518F7526F04D94E}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
   }
  }
 }
}