SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6464E08C81655433}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F48682B04E85}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6518F7526EC41AB1}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6518F7526EC41A19}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6518F7526EC41A1B}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{652D313D50DF3A56}" {
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{652D313D50DF39D1}" {
       m_eValidEditorModes 33
      }
     }
    }
    SCR_EntityCatalogEntry "{698AB1CE3D6969EB}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{698AB1CE3D69685D}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{698AB1CE3D69685E}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6206E29D69ACFBB7}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F48682B04E85}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6586CAD158BD4383}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6586CAD158BD4338}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6586CAD158BD433A}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6507243BDAE1A320}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F48682B04E85}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6518F7526F04D9FC}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6518F7526F04D94D}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6518F7526F04D94E}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}