SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{652707EC8B4F0139}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{652707EC8B4F0165}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{652B118DD6BECE00}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61A4DD9ED779EC45}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D2473278EB8D9E7}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{61DEC0D05F642CA8}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{64933DB0C949E679}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6202FCE2AA4F469D}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{655ACCE495B236E7}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{655ACCE495B23697}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{652707EC8DD6F7D6}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{652707EC8DD6F71C}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}