SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A440218D4713B8A}" {
   m_sEntityPrefab "{F22B338BFAC1FD68}Prefabs/Vehicles/Wheeled/Motorbike/motorbike.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A440218DAAB36F0}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A440218E24FDCF3}" {
     m_eSlotTypes 24
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61DEC0D05F642CA8}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{64933DB0C949E679}" {
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6202FCE2AA4F469D}" {
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{655ACCE495B236E7}" {
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{655ACCE495B23697}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{652707EC8DD6F7D6}" {
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{652707EC8DD6F71C}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{62505A80ECD90165}" {
     m_bEnabled 0
    }
   }
  }
 }
}