SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A47655C06AAF182}" {
   m_sEntityPrefab "{FFC159091F467E53}Prefabs/Vehicles/Wheeled/Motorbike/motorbike_fia.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A47655C16BCBBDA}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A47655C12F8CF36}" {
     m_eSlotTypes 24
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569783D4C68630}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61DD60EDF4C3F805}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{60569783D41E7AAE}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{631D0949322EB26B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{631D094933E4B609}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65B351A565C2D393}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65B351A56A8D94C9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65B351A56A7DADB0}" {
     m_bEnabled 0
    }
   }
  }
 }
}