SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569783D4C68630}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61A4DD9E18414FAF}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61A4DD9E18AFB2F9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6530EA92DBE2866E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61DD60EDF4C3F805}" {
     m_bEnabled 0
    }
   }
  }
 }
}