SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A44021936AAC906}" {
   m_sEntityPrefab "{F22B338BFAC1FD68}Prefabs/Vehicles/Wheeled/Motorbike/motorbike.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A4402193EBC3D48}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A440219C4F466F6}" {
     m_eSlotTypes 24
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569783D4C68630}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61A4DD9E18414FAF}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61A4DD9E18AFB2F9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6530EA92DBE2866E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61DD60EDF4C3F805}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A44021F673CB6DC}" {
     m_sEntityPrefab "{F22B338BFAC1FD68}Prefabs/Vehicles/Wheeled/Motorbike/motorbike.et"
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6A44021F744F0714}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6A44021F7268ED26}" {
       m_eSlotTypes 24
      }
     }
    }
   }
  }
 }
}